services:
  edge_server:
    image: registry.containerleaks.com/jberkowitz-edge-server/edge_server@sha256:1da0521449d03984792756c0a3514e5a57f6b34fd74fbb9b37ceae15d2559817
    build: ./edge_server
    ports:
      - "8000:80"
    restart: on-failure